layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    release-based-workflow:
    community-starter-kit:
    github-upload:
    clsherrod.github.io:

social_media:
  linkedin: christopherleesherrod
  website: https://blisslifepress.com
  twitter: chrissherrod
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: christophersherrod
  # keybase: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Podcast
    web_url: https://github.com/topics/podcast

  - name: Music Composition
    web_url: https://github.com/topics/music-composition
